// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Oyd8ymhY-nWdLi23R_9wsABcucXhNG8',
    appId: '1:527276965751:web:906ad5ab172913f545eb72',
    messagingSenderId: '527276965751',
    projectId: 'portfolio-1f48f',
    authDomain: 'portfolio-1f48f.firebaseapp.com',
    storageBucket: 'portfolio-1f48f.firebasestorage.app',
    measurementId: 'G-LE0Q2SKH51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG-M7gqWsU8crj3SBWTugb_qA9L6_8rOU',
    appId: '1:527276965751:android:567723883c98df2145eb72',
    messagingSenderId: '527276965751',
    projectId: 'portfolio-1f48f',
    storageBucket: 'portfolio-1f48f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5a6x8C3j3LbyFhtzVOhwniuwJAetGpOA',
    appId: '1:527276965751:ios:b80c0ee82184f02c45eb72',
    messagingSenderId: '527276965751',
    projectId: 'portfolio-1f48f',
    storageBucket: 'portfolio-1f48f.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5a6x8C3j3LbyFhtzVOhwniuwJAetGpOA',
    appId: '1:527276965751:ios:b80c0ee82184f02c45eb72',
    messagingSenderId: '527276965751',
    projectId: 'portfolio-1f48f',
    storageBucket: 'portfolio-1f48f.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5Oyd8ymhY-nWdLi23R_9wsABcucXhNG8',
    appId: '1:527276965751:web:a7f086e5993fc90d45eb72',
    messagingSenderId: '527276965751',
    projectId: 'portfolio-1f48f',
    authDomain: 'portfolio-1f48f.firebaseapp.com',
    storageBucket: 'portfolio-1f48f.firebasestorage.app',
    measurementId: 'G-6QHCZQZYR0',
  );
}
